server:
  port: 8080
  servlet:
    context-path: "/edws"
# 数据库连接信息配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.60.210.106:3306/nqdj?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 403126
  mvc:
    pathmatch:
      # Springfox使用的路径匹配是基于AntPathMatcher的
      # 所以需要配置此参数
      matching-strategy: ant_path_matcher
  mail:
    username: wuhaisen403@163.com
    password: BCBBEYGMUGBYZEQN
    host: smtp.163.com
    port: 465
    protocol: smtp
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
  redis:
    host: 123.60.210.106
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 5
        min-idle: 0
    password: 403126

# mybatis相关配置
mybatis:
  # mapper文件所在位置
  mapper-locations: classpath:mapper/*.xml
  # 扫描实体类别名
  type-aliases-package: com.whs.edws.entity
  configuration:
    # 下划线转驼峰命名
    safe-result-handler-enabled: true

# 日志配置
logging:
  level:
    com.whs.edws.mapper: debug

minio:
  # 访问的url
  endpoint: http://123.60.210.106
  # API的端口
  port: 9000
  # 秘钥
  accessKey: NkgnDWEpoMG4EX06t0Om
  secretKey: HNoa9TzHhITwAkoxUgoqmk9bwR6ATyr9mjbK4BRN
  secure: false
  bucket-name: nqdj # 桶名 我这是给出了一个默认桶名
  image-size: 10485760 # 我在这里设定了 图片文件的最大大小
  file-size: 1073741824 # 此处是设定了文件的最大大小


