version: "3.1"
services:
  redis1:
    container_name: redis1
    image: redis:6.2.5
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data1:/data
      - ./conf/redis1.conf:/usr/local/etc/redis/redis.conf
      - ./logs1:/logs
    environment:
      - TZ="Asia/Shanghai"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
  redis2:
    container_name: redis2
    image: redis:6.2.5
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - ./data2:/data
      - ./conf/redis2.conf:/usr/local/etc/redis/redis.conf
      - ./logs2:/logs
    environment:
      - TZ="Asia/Shanghai"
    links:
      - redis1:master
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf"]
  redis3:
    container_name: redis3
    image: redis:6.2.5
    restart: always
    ports:
      - "6381:6379"
    volumes:
      - ./data3:/data
      - ./conf/redis3.conf:/usr/local/etc/redis/redis.conf
      - ./logs3:/logs
    environment:
      - TZ="Asia/Shanghai"
    links:
      - redis1:master
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

